export interface VoiceProfile {
  id: string;
  name: string;
  icon: string;
  color: string;
  desc: string;
  effect: 'none' | 'robotic' | 'heavy' | 'chipmunk';
  carrierFreq: number;
  pitchFactor: number;
  echoEnabled: boolean;
  echoLevel: number;
  gain: number;
  volume: number;
  compressor: boolean;
  noiseGate: boolean;
}

export const VOICE_PROFILES: VoiceProfile[] = [
  {
    id: 'radio-host',
    name: 'Radio Host',
    icon: 'radio',
    color: '#F59E0B',
    desc: 'Warm broadcast',
    effect: 'none',
    carrierFreq: 200,
    pitchFactor: 1.0,
    echoEnabled: false,
    echoLevel: 0,
    gain: 90,
    volume: 85,
    compressor: true,
    noiseGate: true,
  },
  {
    id: 'villain',
    name: 'Villain',
    icon: 'skull-outline',
    color: '#EF4444',
    desc: 'Deep menacing',
    effect: 'heavy',
    carrierFreq: 200,
    pitchFactor: 0.55,
    echoEnabled: true,
    echoLevel: 2,
    gain: 85,
    volume: 80,
    compressor: true,
    noiseGate: false,
  },
  {
    id: 'alien',
    name: 'Alien',
    icon: 'planet-outline',
    color: '#10B981',
    desc: 'Otherworldly',
    effect: 'robotic',
    carrierFreq: 300,
    pitchFactor: 1.0,
    echoEnabled: true,
    echoLevel: 1,
    gain: 80,
    volume: 80,
    compressor: false,
    noiseGate: false,
  },
  {
    id: 'underwater',
    name: 'Underwater',
    icon: 'water-outline',
    color: '#3B82F6',
    desc: 'Submerged',
    effect: 'heavy',
    carrierFreq: 200,
    pitchFactor: 0.45,
    echoEnabled: true,
    echoLevel: 3,
    gain: 70,
    volume: 75,
    compressor: false,
    noiseGate: false,
  },
  {
    id: 'megaphone',
    name: 'Megaphone',
    icon: 'megaphone-outline',
    color: '#F97316',
    desc: 'Distorted PA',
    effect: 'robotic',
    carrierFreq: 400,
    pitchFactor: 1.0,
    echoEnabled: false,
    echoLevel: 0,
    gain: 95,
    volume: 85,
    compressor: true,
    noiseGate: true,
  },
  {
    id: 'whisper',
    name: 'Whisper',
    icon: 'ear-outline',
    color: '#8B5CF6',
    desc: 'Soft ethereal',
    effect: 'none',
    carrierFreq: 200,
    pitchFactor: 1.0,
    echoEnabled: true,
    echoLevel: 1,
    gain: 40,
    volume: 60,
    compressor: false,
    noiseGate: true,
  },
  {
    id: 'stadium',
    name: 'Stadium',
    icon: 'trophy-outline',
    color: '#EAB308',
    desc: 'Arena echo',
    effect: 'none',
    carrierFreq: 200,
    pitchFactor: 1.0,
    echoEnabled: true,
    echoLevel: 3,
    gain: 95,
    volume: 90,
    compressor: true,
    noiseGate: false,
  },
  {
    id: 'telephone',
    name: 'Telephone',
    icon: 'call-outline',
    color: '#06B6D4',
    desc: 'Retro phone',
    effect: 'robotic',
    carrierFreq: 350,
    pitchFactor: 1.0,
    echoEnabled: false,
    echoLevel: 0,
    gain: 85,
    volume: 75,
    compressor: true,
    noiseGate: true,
  },
  {
    id: 'cave',
    name: 'Cave',
    icon: 'flashlight-outline',
    color: '#6B7280',
    desc: 'Deep reverb',
    effect: 'none',
    carrierFreq: 200,
    pitchFactor: 1.0,
    echoEnabled: true,
    echoLevel: 3,
    gain: 75,
    volume: 80,
    compressor: false,
    noiseGate: false,
  },
  {
    id: 'robot-dj',
    name: 'Robot DJ',
    icon: 'musical-notes-outline',
    color: '#EC4899',
    desc: 'Electronic beat',
    effect: 'robotic',
    carrierFreq: 150,
    pitchFactor: 1.0,
    echoEnabled: false,
    echoLevel: 0,
    gain: 90,
    volume: 85,
    compressor: true,
    noiseGate: false,
  },
];
